var eventVar = {
    baseUrl : 'https://stagbusiness.dauble.com' ,
    UserModel : 'login.email' ,
    userName : 'shivamsharma3584@gmail.com',
    passWord : 'deepakpal',
    passModel : 'login.password' ,
    loginButton : 'SIGN IN' ,
    title : 'event',
    absolutePath : '/Users/shiv/downloads/img_cfc8f3721297c2d2868eb1776266a4f5_1519812319011_processed_original.jpg' ,
    eventname : 'New Exhibition,Java Provides A Data Structure, Variables Of The Same Type.',
    eventnameModel : 'createEvent.addEventForm.name' ,
    eventDetail : 'New exhibition,Java provides a data structure, variables of the same type New exhibition,Java provides a data structure, variables of the same type New exhibition,Java provides a data structure, variables of the same type New exhibition,Java provides a data structure, variables of the same type New exhibition,Java provides a data structure, variables of the same type New exhibition,Java provides a data structure, variables of the same type New exhibition,Java provides a data structure, variables of the same type New exhibition,Java provides a data structure, variables of the same type New exhibition,Java provides a data structure, variables of the same type New exhibition,Java provides a data structure, variables of the same type.' ,
    eventDetailModel : 'createEvent.addEventForm.description' ,
    eventAddress : '1623 Battleship Dr, Honolulu, HI 96818, USA' ,
    eventAddressModel : 'createEvent.addEventForm.addressLine1' ,
    eventSponsorType1 : 'Public' ,
    eventSponsorName1 : 'Yuser',
    eventFlink : 'https://www.facebook.com/vandana',
    eventTlink : 'https://twitter.com/Alaska' ,
    eventInlink : 'https://www.instagram.com/a/' ,
    eventWeblink : 'https://www.google.com/?gws_rd=ssl' ,
    eventNote : 'New exhibition,Java provides a data structure, variables of the same type New exhibition,Java provides a data structure, variables of the same type New exhibition,Java provides a data structure, variables of the same type New exhibition,Java provides a data structure, variables of the same type New exhibition,Java provides a data structure, variables of the same type New exhibition,Java provides a data structure, variables of the same type New exhibition,Java provides a data structure, variables of the same type New exhibition,Java provides 123.' ,
    eventInternaluser : 'Internal gallery user' ,
    eventInternaluseTask : 'QA',
    myeventTab : '[ng-click="businessHeader.goto(\'myevents/type\')"]' ,
    createEventTab : 'a[ng-href="#/myevents/create"]' ,
    typeOfEvent : 'createEvent.eventTypeId' ,
    typeOfEvent1 : '.md-select-menu-container.md-active md-option' ,
    coverImage : 'input[type=file][ng-model="createEvent.coverImageUrl"]' ,
    datepicker : '.md-datepicker-input' ,
    timestamp : '[data-timestamp="1525804200000"]' ,
    timestamp1 :'[data-timestamp="1525977000000"]',
    timezone : 'createEvent.addEventForm.timeZone' ,
    timeZone : 'UTC- 09:00 - Alaska Standard Time (AKST)' ,
};
module.exports = eventVar;
